[project]
name = "gliderdata"
version = "0.1.0"
description = "SPOT tracker data collection and storage"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.31.0",
    "python-dotenv>=1.0.0",
    "schedule>=1.2.0",
    "pydantic>=2.0.0",
]
